# POST http://localhost:3000/signin
# Content-Type: application/json

# {

#     "email" : "Avfibnnk@abbc.com",
#     "password":"Avi7854"
# }

POST http://localhost:3000/get-profile
Content-Type: application/json

{
    "username":"hackavi796"
}